### ISSUE TITLE
Broken in Forge

### ISSUE THREAD

**Issue by oncoremarco** [Malisius/booru2prompt#20]
Does not work with the Forge UI. Does not appear in the list of extensions on the Generation tab.

**Comment by aolko** [comment]
It does appear in the extension list, but not as a tab
```
Loading booru2prompt settings
*** Error loading script: tagger.py
    Traceback (most recent call last):
      File "D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py", line 5, in <module>
        from tagger.api import on_app_started  # pylint: disable=import-error
      File "D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\stable-diffusion-webui-wd14-tagger\tagger\api.py", line 17, in <module>
        from tagger import utils  # pylint: disable=import-error
      File "D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\stable-diffusion-webui-wd14-tagger\tagger\utils.py", line 13, in <module>
        from tagger.interrogator import Interrogator, DeepDanbooruInterrogator, \
      File "D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 32, in <module>
        if shared.cmd_opts.additional_device_ids is not None:
    AttributeError: 'Namespace' object has no attribute 'additional_device_ids'

```
```
D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\booru2prompt\scripts\main.py:442: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  searchimages.style(grid=3)
D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\booru2prompt\scripts\main.py:442: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  searchimages.style(grid=3)
*** Error executing callback ui_tabs_callback for D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\booru2prompt\scripts\main.py
    Traceback (most recent call last):
      File "D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\script_callbacks.py", line 183, in ui_tabs_callback
        res += c.callback() or []
      File "D:\Programs\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\booru2prompt\scripts\main.py", line 501, in on_ui_tabs
        sendselected = modules.generation_parameters_copypaste.create_buttons(["txt2img", "img2img", "inpaint", "extras"])
    AttributeError: module 'modules' has no attribute 'generation_parameters_copypaste'
```
@Malisius pls fix

**Comment by abubasal** [comment]
+1

**Comment by shimizu-izumi** [comment]
+1

**Comment by aolko** [comment]
I wonder if @Malisius cares or left this repository for dead?

**Comment by shimizu-izumi** [comment]
Probably dead @aolko, I guess I'll try to fix it myself.

**Comment by wywhynot** [comment]
> Probably dead @aolko, I guess I'll try to fix it myself.

Have you done so? I just found this and wanted to use it

**Comment by imrayya** [comment]
In case anyone wants a quick solution (not perfect)

In `scripts/main.py`

1. Comment out line 301, 387, and 388 (put a `#` in front of it)
2. Line 360 and 361: change `generation_parameters_copypaste` to `infotext_utils`

It should get it working.

I didn't want to make a pull request in case the changes broke the extension for A1111 or SD.Next
